---
version: "3.7"

networks:
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
    external: true

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - TZ=${TZ}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APPDATA_DIR}/traefik:/etc/traefik:rw
    ports:
      - "${NETWORK_BIND_ADDR}:80:80"
      - "${NETWORK_BIND_ADDR}:443:443"
    command:
      - "--logLevel=INFO"
      - "--api"
      - "--defaultentrypoints=http,https"
      - "--entrypoints=Name:http Address::80 Compress:true ForwardedHeaders.TrustedIPs:10.0.0.2 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS Compress:true ForwardedHeaders.TrustedIPs:10.0.0.2 TLS.SniStrict:true TLS.MinVersion:VersionTLS12 CipherSuites:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
      - "--acme"
      - "--acme.storage=/etc/traefik/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.dnsChallenge=true"
      - "--acme.dnsChallenge.provider=cloudflare"
      - "--acme.dnsChallenge.delayBeforeCheck=60"
      - "--acme.dnsChallenge.resolvers=1.1.1.1,1.0.0.1"
      - "--acme.onHostRule=true"
      - "--acme.email=${CLOUDFLARE_EMAIL}"
      - "--acme.acmeLogging=true"
      # - "--acme.domains=${ROOT_DOMAIN},*.${ROOT_DOMAIN},"
      - "--acme.domains=*.${ROOT_DOMAIN},"
      - "--acme.KeyType=RSA4096"
      - "--docker"
      - "--docker.domain=${ROOT_DOMAIN}"
      - "--docker.watch"
      - "--docker.exposedbydefault=false"
      - "--retry"
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_proxy
      traefik.backend: traefik
      traefik.port: 8080
      traefik.frontend.rule: Host:traefik.${ROOT_DOMAIN}
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.frontend.headers.browserXSSFilter: true
      traefik.frontend.headers.contentTypeNosniff: true
      traefik.frontend.headers.forceSTSHeader: true
      traefik.frontend.headers.STSIncludeSubdomains: true
      traefik.frontend.headers.STSPreload: true
      traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.headers.frameDeny: true

  # https://github.com/plexinc/pms-docker
  plex:
    # https://hub.docker.com/r/plexinc/pms-docker
    image: plexinc/pms-docker
    container_name: plex
    hostname: ${PLEX_HOSTNAME}
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM_CODE}
      # Remote access will look at `ADVERTISE_IP`, but because it's behind a proxy, it's likely that
      # the dashboard will say "Not available outside your network" even though it is... >:(
      - ADVERTISE_IP=https://plex.${ROOT_DOMAIN}:443
    volumes:
      - ${APPDATA_DIR}/plex:/config
      - ${STORAGE_DIR}/music:/data/Music
      - ${STORAGE_DIR}/movies:/data/Movies
      - ${STORAGE_DIR}/tv:/data/TV
      # - ${STORAGE_DIR}/tmp/transcode:/transcode
      - /tmp:/transcode
    ports:
      # Plex ports - source: https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
      - "32400:32400" # Plex Media Server
      - "3005:3005" # Plex Companion
      - "8324:8324" # Roku via Plex Companion
      - "32469:32649" # Plex DLNA Server
      - "1900:1900/udp" # Plex DLNA Server
      - "32410:32410/udp" # network discovery
      - "32412:32412/udp" # network discovery
      - "32413:32413/udp" # network discovery
      - "32414:32414/udp" # network discovery
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_proxy
      traefik.backend: plex
      traefik.port: 32400
      traefik.frontend.rule: Host:plex.${ROOT_DOMAIN}
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.frontend.headers.browserXSSFilter: true
      traefik.frontend.headers.contentTypeNosniff: true
      traefik.frontend.headers.forceSTSHeader: true
      traefik.frontend.headers.SSLHost: plex.${ROOT_DOMAIN}
      traefik.frontend.headers.STSIncludeSubdomains: true
      traefik.frontend.headers.STSPreload: true
      traefik.frontend.headers.frameDeny: true

  # https://github.com/linuxserver/docker-nzbget
  nzbget:
    # https://hub.docker.com/r/linuxserver/nzbget
    image: linuxserver/nzbget
    container_name: nzbget
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA_DIR}/nzbget:/config
      - ${STORAGE_DIR}/downloads:/downloads
    ports:
      - "6788:6789"
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_proxy
      traefik.docker.usebindportip: true # because we mapped specific port
      traefik.backend: nzbget
      traefik.frontend.rule: Host:nzbget.${ROOT_DOMAIN}
      traefik.http.frontend.headers.customFrameOptionsValue: ALLOW-FROM https://${ROOT_DOMAIN}
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.frontend.headers.browserXSSFilter: true
      traefik.frontend.headers.contentTypeNosniff: true
      traefik.frontend.headers.forceSTSHeader: true
      traefik.frontend.headers.STSIncludeSubdomains: true
      traefik.frontend.headers.STSPreload: true
      traefik.frontend.headers.frameDeny: true

  # https://github.com/portainer/portainer
  portainer:
    # https://hub.docker.com/r/portainer/portainer/
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    networks:
      - traefik_proxy
    command: -H unix:///var/run/docker.sock
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPDATA_DIR}/portainer:/data
    ports:
      - "9000:9000"
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_proxy
      traefik.backend: portainer
      traefik.port: 9000
      traefik.frontend.rule: Host:portainer.${ROOT_DOMAIN}
      traefik.frontend.headers.SSLRedirect: true
      traefik.frontend.headers.STSSeconds: 315360000
      traefik.frontend.headers.browserXSSFilter: true
      traefik.frontend.headers.contentTypeNosniff: true
      traefik.frontend.headers.forceSTSHeader: true
      traefik.frontend.headers.STSIncludeSubdomains: true
      traefik.frontend.headers.STSPreload: true
      traefik.frontend.headers.frameDeny: true
